/** Auto-generated from Chase College Checking statements (Dec 2025 – Jul 2026). */
import type { FinanceTx } from "./financeStore";

export const CHASE_STATEMENT_TXS: FinanceTx[] = 
[
  {
    "id": "chase-ccdc8b0c37093468",
    "date": "2025-12-08",
    "kind": "expense",
    "amount": 30.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-ccdc8b0c37093468",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-243003971855ee3f",
    "date": "2025-12-08",
    "kind": "expense",
    "amount": 250.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-243003971855ee3f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a8056bae8303dfee",
    "date": "2025-12-08",
    "kind": "income",
    "amount": 20.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-a8056bae8303dfee",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-6d0f1a825b880a91",
    "date": "2025-12-08",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-6d0f1a825b880a91",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-779f6536317506fe",
    "date": "2025-12-08",
    "kind": "income",
    "amount": 300.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-779f6536317506fe",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b60babee926b17bf",
    "date": "2025-12-08",
    "kind": "expense",
    "amount": 14.0,
    "category": "Transfers",
    "note": "Zelle to Carly Usc",
    "merchant": "Zelle to Carly Usc",
    "source": "import",
    "externalId": "chase-b60babee926b17bf",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3b7ad224d9ac1e24",
    "date": "2025-12-15",
    "kind": "income",
    "amount": 20.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-3b7ad224d9ac1e24",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-dde56423d19fc6fc",
    "date": "2025-12-15",
    "kind": "income",
    "amount": 50.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-dde56423d19fc6fc",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-4fe3bb787e73b70a",
    "date": "2025-12-15",
    "kind": "expense",
    "amount": 60.0,
    "category": "Transfers",
    "note": "Zelle to Lionna ID",
    "merchant": "Zelle to Lionna ID",
    "source": "import",
    "externalId": "chase-4fe3bb787e73b70a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8ce2737358fd051f",
    "date": "2025-12-15",
    "kind": "expense",
    "amount": 8.25,
    "category": "Transfers",
    "note": "Zelle to Zeba",
    "merchant": "Zelle to Zeba",
    "source": "import",
    "externalId": "chase-8ce2737358fd051f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d3e26ae31d6a6d37",
    "date": "2025-12-16",
    "kind": "expense",
    "amount": 7.7,
    "category": "Transfers",
    "note": "Zelle to Zeba",
    "merchant": "Zelle to Zeba",
    "source": "import",
    "externalId": "chase-d3e26ae31d6a6d37",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0f769b416446debb",
    "date": "2025-12-17",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-0f769b416446debb",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-83f6d3b88f556cd8",
    "date": "2025-12-18",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-83f6d3b88f556cd8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d39e9a910c85fa1f",
    "date": "2025-12-18",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-d39e9a910c85fa1f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-5738548c25ec4adb",
    "date": "2025-12-19",
    "kind": "expense",
    "amount": 12.87,
    "category": "Shopping",
    "note": "Farmer's Fridge Chicago IL",
    "merchant": "Farmer's Fridge Chicago IL",
    "source": "import",
    "externalId": "chase-5738548c25ec4adb",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-df48b0c2ca60d532",
    "date": "2025-12-19",
    "kind": "expense",
    "amount": 13.99,
    "category": "Shopping",
    "note": "Nayax Amusement Hunt Valley MD",
    "merchant": "Nayax Amusement Hunt Valley MD",
    "source": "import",
    "externalId": "chase-df48b0c2ca60d532",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ed3cb1ac0ec575b4",
    "date": "2025-12-22",
    "kind": "expense",
    "amount": 14.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-ed3cb1ac0ec575b4",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8c9d0dedf2ae9ff4",
    "date": "2025-12-22",
    "kind": "expense",
    "amount": 200.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-8c9d0dedf2ae9ff4",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-35d1f5b24b458c73",
    "date": "2025-12-22",
    "kind": "income",
    "amount": 200.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-35d1f5b24b458c73",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-addd8e2bf0b794dd",
    "date": "2025-12-26",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-addd8e2bf0b794dd",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-da555cfbee978a9c",
    "date": "2025-12-26",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-da555cfbee978a9c",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c56cf5a067719f36",
    "date": "2025-12-26",
    "kind": "income",
    "amount": 400.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-c56cf5a067719f36",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-10bc8281d6df9bc5",
    "date": "2025-12-29",
    "kind": "expense",
    "amount": 10.19,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-10bc8281d6df9bc5",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9600b243fa926eb7",
    "date": "2025-12-29",
    "kind": "expense",
    "amount": 55.67,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-9600b243fa926eb7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-488f84eb43bfe0ba",
    "date": "2025-12-29",
    "kind": "expense",
    "amount": 391.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-488f84eb43bfe0ba",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3fba3d170cc7a1c9",
    "date": "2025-12-30",
    "kind": "income",
    "amount": 24.79,
    "category": "Income",
    "note": "Cash Redemption",
    "merchant": "Cash Redemption",
    "source": "import",
    "externalId": "chase-3fba3d170cc7a1c9",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-16bb0e78f1bf2670",
    "date": "2025-12-31",
    "kind": "income",
    "amount": 20.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-16bb0e78f1bf2670",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-e131e6c4d78e4fbd",
    "date": "2025-12-31",
    "kind": "income",
    "amount": 25.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-e131e6c4d78e4fbd",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d8e5dfbb9885bde7",
    "date": "2025-12-31",
    "kind": "expense",
    "amount": 2.99,
    "category": "Shopping",
    "note": "G Mart Elmhurst NY",
    "merchant": "G Mart Elmhurst NY",
    "source": "import",
    "externalId": "chase-d8e5dfbb9885bde7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-e37ad165798a3b36",
    "date": "2025-12-31",
    "kind": "expense",
    "amount": 25.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-e37ad165798a3b36",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0d9e382a08b10ff1",
    "date": "2025-12-31",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-0d9e382a08b10ff1",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-bee6c628556fdbc2",
    "date": "2026-01-02",
    "kind": "expense",
    "amount": 28.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-bee6c628556fdbc2",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a4f4539b5a52799f",
    "date": "2026-01-02",
    "kind": "expense",
    "amount": 55.96,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-a4f4539b5a52799f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-5b9a601b94ea946f",
    "date": "2026-01-02",
    "kind": "income",
    "amount": 30.12,
    "category": "Income",
    "note": "Zelle from Zeba Attar",
    "merchant": "Zelle from Zeba Attar",
    "source": "import",
    "externalId": "chase-5b9a601b94ea946f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-2dcfbe8959e4a7af",
    "date": "2026-01-05",
    "kind": "expense",
    "amount": 2.9,
    "category": "Transport",
    "note": "Mta*Nyct Paygo New York NY",
    "merchant": "Mta*Nyct Paygo New York NY",
    "source": "import",
    "externalId": "chase-2dcfbe8959e4a7af",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-111ad7eb70635937",
    "date": "2026-01-06",
    "kind": "expense",
    "amount": 57.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-111ad7eb70635937",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-30e0502fe0003823",
    "date": "2026-01-12",
    "kind": "expense",
    "amount": 12.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-30e0502fe0003823",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-abbf9ac072cb8253",
    "date": "2026-01-12",
    "kind": "expense",
    "amount": 90.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-abbf9ac072cb8253",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b6092d56b942e11a",
    "date": "2026-01-12",
    "kind": "expense",
    "amount": 390.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-b6092d56b942e11a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-1f4e04c5a932e29d",
    "date": "2026-01-12",
    "kind": "income",
    "amount": 35.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-1f4e04c5a932e29d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-133705754ce72607",
    "date": "2026-01-12",
    "kind": "income",
    "amount": 400.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-133705754ce72607",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ea3252f762275251",
    "date": "2026-01-12",
    "kind": "income",
    "amount": 10.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-ea3252f762275251",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-67148cbc189cee1f",
    "date": "2026-01-12",
    "kind": "income",
    "amount": 90.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-67148cbc189cee1f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c103b527bfe50b47",
    "date": "2026-01-12",
    "kind": "expense",
    "amount": 35.22,
    "category": "Transfers",
    "note": "Zelle to Nicole Usc Roomate",
    "merchant": "Zelle to Nicole Usc Roomate",
    "source": "import",
    "externalId": "chase-c103b527bfe50b47",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-bf2981040262d001",
    "date": "2026-01-15",
    "kind": "expense",
    "amount": 10.0,
    "category": "Shopping",
    "note": "Wash Kiosk Mobile 800-4216897 CA",
    "merchant": "Wash Kiosk Mobile 800-4216897 CA",
    "source": "import",
    "externalId": "chase-bf2981040262d001",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-6fecc50c0f53e436",
    "date": "2026-01-15",
    "kind": "income",
    "amount": 50.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-6fecc50c0f53e436",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d9ffe872843970c3",
    "date": "2026-01-20",
    "kind": "expense",
    "amount": 17.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-d9ffe872843970c3",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0dc3165f2bd64ec9",
    "date": "2026-01-20",
    "kind": "expense",
    "amount": 80.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-0dc3165f2bd64ec9",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-2bd3ce7268fd4267",
    "date": "2026-01-20",
    "kind": "expense",
    "amount": 15.78,
    "category": "Transport",
    "note": "Waymo 844-261-3753 CA",
    "merchant": "Waymo 844-261-3753 CA",
    "source": "import",
    "externalId": "chase-2bd3ce7268fd4267",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ac07097152c877cb",
    "date": "2026-01-20",
    "kind": "expense",
    "amount": 16.48,
    "category": "Transport",
    "note": "Waymo 844-261-3753 CA",
    "merchant": "Waymo 844-261-3753 CA",
    "source": "import",
    "externalId": "chase-ac07097152c877cb",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-18d0809c782f43e7",
    "date": "2026-01-20",
    "kind": "income",
    "amount": 80.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-18d0809c782f43e7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d0cffe912fce647b",
    "date": "2026-01-20",
    "kind": "income",
    "amount": 6.0,
    "category": "Income",
    "note": "Zelle from Jingtong Luo Baclxqw9147F",
    "merchant": "Zelle from Jingtong Luo Baclxqw9147F",
    "source": "import",
    "externalId": "chase-d0cffe912fce647b",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ec3e46de60b955d0",
    "date": "2026-01-20",
    "kind": "income",
    "amount": 5.5,
    "category": "Income",
    "note": "Zelle from Jingtong Luo Bacruwt6Mwro",
    "merchant": "Zelle from Jingtong Luo Bacruwt6Mwro",
    "source": "import",
    "externalId": "chase-ec3e46de60b955d0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-6037b3c2cb8c4f90",
    "date": "2026-01-20",
    "kind": "income",
    "amount": 10.75,
    "category": "Income",
    "note": "Zelle from Yuetong Liu 0Jx01B91Kkf8",
    "merchant": "Zelle from Yuetong Liu 0Jx01B91Kkf8",
    "source": "import",
    "externalId": "chase-6037b3c2cb8c4f90",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8d060379e99eccff",
    "date": "2026-01-20",
    "kind": "expense",
    "amount": 13.0,
    "category": "Transfers",
    "note": "Zelle to Zeba",
    "merchant": "Zelle to Zeba",
    "source": "import",
    "externalId": "chase-8d060379e99eccff",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-892509811f711403",
    "date": "2026-01-20",
    "kind": "expense",
    "amount": 10.0,
    "category": "Transfers",
    "note": "Zelle to Ziyu Gao",
    "merchant": "Zelle to Ziyu Gao",
    "source": "import",
    "externalId": "chase-892509811f711403",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9df6dace6fc2dffa",
    "date": "2026-01-22",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-9df6dace6fc2dffa",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b8c6f7613ed2e082",
    "date": "2026-01-22",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-b8c6f7613ed2e082",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-82ead4d1972e3e8e",
    "date": "2026-01-22",
    "kind": "income",
    "amount": 350.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-82ead4d1972e3e8e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b226c50149b4302a",
    "date": "2026-01-22",
    "kind": "income",
    "amount": 17.34,
    "category": "Income",
    "note": "Zelle from Zeba Attar",
    "merchant": "Zelle from Zeba Attar",
    "source": "import",
    "externalId": "chase-b226c50149b4302a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b0b4823141a7827a",
    "date": "2026-01-23",
    "kind": "expense",
    "amount": 300.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-b0b4823141a7827a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-2f5cdfeaaf19d404",
    "date": "2026-01-23",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-2f5cdfeaaf19d404",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-30d22f4de5eab8ec",
    "date": "2026-01-26",
    "kind": "expense",
    "amount": 42.15,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-30d22f4de5eab8ec",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-4d85119f85c9e264",
    "date": "2026-01-26",
    "kind": "income",
    "amount": 20.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-4d85119f85c9e264",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-1f47bf07b5d679ac",
    "date": "2026-01-26",
    "kind": "expense",
    "amount": 2.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-1f47bf07b5d679ac",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-5974bfde4cf0ff1c",
    "date": "2026-01-26",
    "kind": "income",
    "amount": 50.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-5974bfde4cf0ff1c",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9cc6869d6faebb8f",
    "date": "2026-01-26",
    "kind": "expense",
    "amount": 23.0,
    "category": "Transfers",
    "note": "Zelle to Ced",
    "merchant": "Zelle to Ced",
    "source": "import",
    "externalId": "chase-9cc6869d6faebb8f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a0d58b466385a574",
    "date": "2026-01-27",
    "kind": "expense",
    "amount": 21.98,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-a0d58b466385a574",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d4cb507b6e51050d",
    "date": "2026-01-30",
    "kind": "expense",
    "amount": 25.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-d4cb507b6e51050d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-14c39cd37786a4f1",
    "date": "2026-02-02",
    "kind": "income",
    "amount": 7.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-14c39cd37786a4f1",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-663b9eba5bb5ffdf",
    "date": "2026-02-02",
    "kind": "income",
    "amount": 10.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-663b9eba5bb5ffdf",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-4b20142d98495a8a",
    "date": "2026-02-02",
    "kind": "expense",
    "amount": 10.0,
    "category": "Shopping",
    "note": "Wash Kiosk Mobile 800-4216897 CA",
    "merchant": "Wash Kiosk Mobile 800-4216897 CA",
    "source": "import",
    "externalId": "chase-4b20142d98495a8a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ee99d0403f474f7d",
    "date": "2026-02-02",
    "kind": "expense",
    "amount": 8.03,
    "category": "Transfers",
    "note": "Zelle to Zeba",
    "merchant": "Zelle to Zeba",
    "source": "import",
    "externalId": "chase-ee99d0403f474f7d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a556e7164243331d",
    "date": "2026-02-03",
    "kind": "income",
    "amount": 40.0,
    "category": "Income",
    "note": "Venmo Cashout PPD ID:",
    "merchant": "Venmo Cashout PPD ID:",
    "source": "import",
    "externalId": "chase-a556e7164243331d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b3daa08721125c1f",
    "date": "2026-02-03",
    "kind": "income",
    "amount": 7.0,
    "category": "Income",
    "note": "Zelle from Sophie Chuang Wfct0Zrp5X3H",
    "merchant": "Zelle from Sophie Chuang Wfct0Zrp5X3H",
    "source": "import",
    "externalId": "chase-b3daa08721125c1f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ea9bf50b03bbe5f6",
    "date": "2026-02-04",
    "kind": "income",
    "amount": 18.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-ea9bf50b03bbe5f6",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a5a5dcee6f667389",
    "date": "2026-02-06",
    "kind": "expense",
    "amount": 67.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-a5a5dcee6f667389",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c3a0fa156fd2f7e8",
    "date": "2026-02-13",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-c3a0fa156fd2f7e8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9f95442d4c0ae644",
    "date": "2026-02-13",
    "kind": "expense",
    "amount": 11.0,
    "category": "Transfers",
    "note": "Zelle to Ziyu Gao",
    "merchant": "Zelle to Ziyu Gao",
    "source": "import",
    "externalId": "chase-9f95442d4c0ae644",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d6e968c210c523e7",
    "date": "2026-02-17",
    "kind": "expense",
    "amount": 89.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-d6e968c210c523e7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d99d50c602eb51f9",
    "date": "2026-02-17",
    "kind": "expense",
    "amount": 300.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-d99d50c602eb51f9",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d6a1b733dd4312bd",
    "date": "2026-02-17",
    "kind": "expense",
    "amount": 10.0,
    "category": "Shopping",
    "note": "Wash Kiosk Mobile 800-4216897 CA",
    "merchant": "Wash Kiosk Mobile 800-4216897 CA",
    "source": "import",
    "externalId": "chase-d6a1b733dd4312bd",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c383da5571be5739",
    "date": "2026-02-17",
    "kind": "income",
    "amount": 480.0,
    "category": "Income",
    "note": "Zelle from Audrey Davis",
    "merchant": "Zelle from Audrey Davis",
    "source": "import",
    "externalId": "chase-c383da5571be5739",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b4de2f68d26aa67f",
    "date": "2026-02-17",
    "kind": "income",
    "amount": 1.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-b4de2f68d26aa67f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0cd162f338f7f89f",
    "date": "2026-02-17",
    "kind": "expense",
    "amount": 35.84,
    "category": "Transfers",
    "note": "Zelle to Carly Usc",
    "merchant": "Zelle to Carly Usc",
    "source": "import",
    "externalId": "chase-0cd162f338f7f89f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-21d86e95dd72304f",
    "date": "2026-02-18",
    "kind": "income",
    "amount": 25.4,
    "category": "Income",
    "note": "Cash Redemption",
    "merchant": "Cash Redemption",
    "source": "import",
    "externalId": "chase-21d86e95dd72304f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0ed473bea3603abd",
    "date": "2026-02-23",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-0ed473bea3603abd",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-fb96ffd68e4f94c7",
    "date": "2026-02-23",
    "kind": "expense",
    "amount": 60.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-fb96ffd68e4f94c7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3eafd652414e03c9",
    "date": "2026-02-23",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-3eafd652414e03c9",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-e19b505e85a68a60",
    "date": "2026-02-23",
    "kind": "income",
    "amount": 20.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-e19b505e85a68a60",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-dda10a998aea26cb",
    "date": "2026-02-26",
    "kind": "income",
    "amount": 6.0,
    "category": "Income",
    "note": "Zelle from Zeba Attar",
    "merchant": "Zelle from Zeba Attar",
    "source": "import",
    "externalId": "chase-dda10a998aea26cb",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-35a6a7ccf0205715",
    "date": "2026-02-27",
    "kind": "expense",
    "amount": 25.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-35a6a7ccf0205715",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-aca49350a92f06c4",
    "date": "2026-02-27",
    "kind": "income",
    "amount": 80.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-aca49350a92f06c4",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-2b8f755f3d14da2a",
    "date": "2026-03-02",
    "kind": "expense",
    "amount": 36.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-2b8f755f3d14da2a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a159647d125963e0",
    "date": "2026-03-02",
    "kind": "expense",
    "amount": 60.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-a159647d125963e0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-73ecf610af985d7e",
    "date": "2026-03-02",
    "kind": "income",
    "amount": 35.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-73ecf610af985d7e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ac6f57b5e1b16547",
    "date": "2026-03-02",
    "kind": "income",
    "amount": 30.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-ac6f57b5e1b16547",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-32b7912d2f15b1c8",
    "date": "2026-03-03",
    "kind": "expense",
    "amount": 30.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-32b7912d2f15b1c8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-174a192cb9a9cea6",
    "date": "2026-03-04",
    "kind": "expense",
    "amount": 10.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-174a192cb9a9cea6",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b18849fef830e444",
    "date": "2026-03-04",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-b18849fef830e444",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-1e3e6057d4398126",
    "date": "2026-03-04",
    "kind": "expense",
    "amount": 80.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-1e3e6057d4398126",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8a72488c3bb6ccc8",
    "date": "2026-03-04",
    "kind": "income",
    "amount": 10.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-8a72488c3bb6ccc8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-aeb5a5ba262a4c2d",
    "date": "2026-03-04",
    "kind": "income",
    "amount": 20.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-aeb5a5ba262a4c2d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c7cc0527fd9c8464",
    "date": "2026-03-04",
    "kind": "income",
    "amount": 80.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-c7cc0527fd9c8464",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-969ff644b0cf6b74",
    "date": "2026-03-04",
    "kind": "income",
    "amount": 20.0,
    "category": "Income",
    "note": "Zelle from Millennium Shrestha",
    "merchant": "Zelle from Millennium Shrestha",
    "source": "import",
    "externalId": "chase-969ff644b0cf6b74",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-124069dee0c89bf8",
    "date": "2026-03-04",
    "kind": "income",
    "amount": 15.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-124069dee0c89bf8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d5a1ef0c0a916b0e",
    "date": "2026-03-04",
    "kind": "expense",
    "amount": 8.0,
    "category": "Transfers",
    "note": "Zelle to Nicolette",
    "merchant": "Zelle to Nicolette",
    "source": "import",
    "externalId": "chase-d5a1ef0c0a916b0e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-593115cb9fad8698",
    "date": "2026-03-09",
    "kind": "income",
    "amount": 17.93,
    "category": "Income",
    "note": "Cash Redemption",
    "merchant": "Cash Redemption",
    "source": "import",
    "externalId": "chase-593115cb9fad8698",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-aeb74cf6ade6cee2",
    "date": "2026-03-09",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-aeb74cf6ade6cee2",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-eefd590a96733852",
    "date": "2026-03-09",
    "kind": "income",
    "amount": 6.0,
    "category": "Income",
    "note": "Zelle from Zeba Attar",
    "merchant": "Zelle from Zeba Attar",
    "source": "import",
    "externalId": "chase-eefd590a96733852",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b0a9d05f9afdf215",
    "date": "2026-03-09",
    "kind": "expense",
    "amount": 10.98,
    "category": "Transfers",
    "note": "Zelle to Sofia Usc",
    "merchant": "Zelle to Sofia Usc",
    "source": "import",
    "externalId": "chase-b0a9d05f9afdf215",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-2d2ea978c4fea389",
    "date": "2026-03-13",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-2d2ea978c4fea389",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3c7d0eccdee13c57",
    "date": "2026-03-13",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-3c7d0eccdee13c57",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-fc7887c05dbfecb4",
    "date": "2026-03-13",
    "kind": "expense",
    "amount": 2.0,
    "category": "Transfers",
    "note": "Zelle to Zeba",
    "merchant": "Zelle to Zeba",
    "source": "import",
    "externalId": "chase-fc7887c05dbfecb4",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0e734e869b7c8a3c",
    "date": "2026-03-16",
    "kind": "income",
    "amount": 500.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-0e734e869b7c8a3c",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-de716903a86831d2",
    "date": "2026-03-17",
    "kind": "expense",
    "amount": 457.2,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-de716903a86831d2",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-128723c4504f2ea3",
    "date": "2026-03-17",
    "kind": "expense",
    "amount": 61.65,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-128723c4504f2ea3",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-414de21a5e52cd01",
    "date": "2026-03-20",
    "kind": "income",
    "amount": 5.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-414de21a5e52cd01",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-030ee59cb4fb5adb",
    "date": "2026-03-20",
    "kind": "expense",
    "amount": 2.0,
    "category": "Transfers",
    "note": "Zelle to Nepa Fashion House LLC",
    "merchant": "Zelle to Nepa Fashion House LLC",
    "source": "import",
    "externalId": "chase-030ee59cb4fb5adb",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-eb3557f47e826473",
    "date": "2026-03-23",
    "kind": "expense",
    "amount": 50.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-eb3557f47e826473",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-17b7c67314da8ef9",
    "date": "2026-03-23",
    "kind": "expense",
    "amount": 353.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-17b7c67314da8ef9",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-e0189f9a43cf5a64",
    "date": "2026-03-23",
    "kind": "expense",
    "amount": 400.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-e0189f9a43cf5a64",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-6ace6f988a9399d7",
    "date": "2026-03-23",
    "kind": "income",
    "amount": 400.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-6ace6f988a9399d7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9fffa18b77159db0",
    "date": "2026-03-23",
    "kind": "income",
    "amount": 400.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-9fffa18b77159db0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-88312cbe8ee959d0",
    "date": "2026-03-24",
    "kind": "expense",
    "amount": 80.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-88312cbe8ee959d0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ec6a047a3ae29e73",
    "date": "2026-03-24",
    "kind": "income",
    "amount": 80.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-ec6a047a3ae29e73",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-644de07a44166497",
    "date": "2026-03-26",
    "kind": "expense",
    "amount": 65.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-644de07a44166497",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ff7143ec299890d0",
    "date": "2026-03-26",
    "kind": "income",
    "amount": 65.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-ff7143ec299890d0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9f6544f7ed454cd1",
    "date": "2026-03-27",
    "kind": "income",
    "amount": 100.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-9f6544f7ed454cd1",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c0543ee40664a43b",
    "date": "2026-03-30",
    "kind": "expense",
    "amount": 25.98,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-c0543ee40664a43b",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d891641858eaac98",
    "date": "2026-03-30",
    "kind": "expense",
    "amount": 30.88,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-d891641858eaac98",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3983bc908185f02a",
    "date": "2026-03-30",
    "kind": "expense",
    "amount": 15.0,
    "category": "Transfers",
    "note": "Zelle to Ivan Shah",
    "merchant": "Zelle to Ivan Shah",
    "source": "import",
    "externalId": "chase-3983bc908185f02a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-470772869774b4a5",
    "date": "2026-03-30",
    "kind": "expense",
    "amount": 5.2,
    "category": "Transfers",
    "note": "Zelle to Sofia Usc",
    "merchant": "Zelle to Sofia Usc",
    "source": "import",
    "externalId": "chase-470772869774b4a5",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-eb4c55030c7d05b1",
    "date": "2026-04-02",
    "kind": "expense",
    "amount": 300.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-eb4c55030c7d05b1",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-131f2fbf95d15de2",
    "date": "2026-04-02",
    "kind": "income",
    "amount": 288.0,
    "category": "Income",
    "note": "Zelle from Cedric Hong",
    "merchant": "Zelle from Cedric Hong",
    "source": "import",
    "externalId": "chase-131f2fbf95d15de2",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-93ab1a76c9059ce1",
    "date": "2026-04-03",
    "kind": "income",
    "amount": 16.3,
    "category": "Income",
    "note": "Cash Redemption",
    "merchant": "Cash Redemption",
    "source": "import",
    "externalId": "chase-93ab1a76c9059ce1",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-55391f074a03b29c",
    "date": "2026-04-06",
    "kind": "expense",
    "amount": 120.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-55391f074a03b29c",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8e8b87751ef96e94",
    "date": "2026-04-06",
    "kind": "income",
    "amount": 10.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-8e8b87751ef96e94",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ff11f752694515ee",
    "date": "2026-04-06",
    "kind": "expense",
    "amount": 20.0,
    "category": "Other",
    "note": "Goldman Sachs Ba Transfer",
    "merchant": "Goldman Sachs Ba Transfer",
    "source": "import",
    "externalId": "chase-ff11f752694515ee",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-784c0ef1c43ce652",
    "date": "2026-04-06",
    "kind": "expense",
    "amount": 10.0,
    "category": "Shopping",
    "note": "Wash Kiosk Mobile 800-4216897 CA",
    "merchant": "Wash Kiosk Mobile 800-4216897 CA",
    "source": "import",
    "externalId": "chase-784c0ef1c43ce652",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a867d7e25250453c",
    "date": "2026-04-06",
    "kind": "income",
    "amount": 101.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-a867d7e25250453c",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-705a2c236efe6888",
    "date": "2026-04-08",
    "kind": "income",
    "amount": 100.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-705a2c236efe6888",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-32c564630a87b526",
    "date": "2026-04-09",
    "kind": "expense",
    "amount": 88.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-32c564630a87b526",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-cb8a3dd5e579a38e",
    "date": "2026-04-09",
    "kind": "expense",
    "amount": 50.0,
    "category": "Other",
    "note": "Goldman Sachs Ba Transfer",
    "merchant": "Goldman Sachs Ba Transfer",
    "source": "import",
    "externalId": "chase-cb8a3dd5e579a38e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-97dee56dbc75a25b",
    "date": "2026-04-10",
    "kind": "income",
    "amount": 80.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-97dee56dbc75a25b",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c0fa8c31a78f67f7",
    "date": "2026-04-10",
    "kind": "expense",
    "amount": 30.0,
    "category": "Transfers",
    "note": "Zelle to Alex",
    "merchant": "Zelle to Alex",
    "source": "import",
    "externalId": "chase-c0fa8c31a78f67f7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-fb4856d333ca948e",
    "date": "2026-04-13",
    "kind": "income",
    "amount": 21.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-fb4856d333ca948e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9f9e78615461898e",
    "date": "2026-04-13",
    "kind": "expense",
    "amount": 21.0,
    "category": "Other",
    "note": "Goldman Sachs Ba Transfer",
    "merchant": "Goldman Sachs Ba Transfer",
    "source": "import",
    "externalId": "chase-9f9e78615461898e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ab6b176c7a825526",
    "date": "2026-04-16",
    "kind": "expense",
    "amount": 238.75,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-ab6b176c7a825526",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-4c0ff727a88a9fd6",
    "date": "2026-04-16",
    "kind": "income",
    "amount": 190.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-4c0ff727a88a9fd6",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-a461ec2b86bd6888",
    "date": "2026-04-16",
    "kind": "expense",
    "amount": 190.0,
    "category": "Other",
    "note": "Goldman Sachs Ba Transfer",
    "merchant": "Goldman Sachs Ba Transfer",
    "source": "import",
    "externalId": "chase-a461ec2b86bd6888",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-f2e28973c30f7834",
    "date": "2026-04-16",
    "kind": "expense",
    "amount": 211.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-f2e28973c30f7834",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3580465566ca998f",
    "date": "2026-04-16",
    "kind": "income",
    "amount": 450.0,
    "category": "Income",
    "note": "Zelle from Audrey Davis",
    "merchant": "Zelle from Audrey Davis",
    "source": "import",
    "externalId": "chase-3580465566ca998f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-6fe7ac5b8b358278",
    "date": "2026-04-24",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-6fe7ac5b8b358278",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-e047369b5c7649fe",
    "date": "2026-04-24",
    "kind": "expense",
    "amount": 80.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-e047369b5c7649fe",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9d8ea9c4aa243802",
    "date": "2026-04-24",
    "kind": "income",
    "amount": 281.0,
    "category": "Income",
    "note": "Goldman Sachs Ba Transfer Shrestha,Melani",
    "merchant": "Goldman Sachs Ba Transfer Shrestha,Melani",
    "source": "import",
    "externalId": "chase-9d8ea9c4aa243802",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-fed884dbd5824a35",
    "date": "2026-04-24",
    "kind": "income",
    "amount": 50.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-fed884dbd5824a35",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-777ddfac77dd43a5",
    "date": "2026-04-24",
    "kind": "income",
    "amount": 50.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-777ddfac77dd43a5",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-f8f8787e38b74afb",
    "date": "2026-04-27",
    "kind": "expense",
    "amount": 183.97,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-f8f8787e38b74afb",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-312d12538f723687",
    "date": "2026-04-27",
    "kind": "expense",
    "amount": 46.0,
    "category": "Transfers",
    "note": "Zelle to Ani",
    "merchant": "Zelle to Ani",
    "source": "import",
    "externalId": "chase-312d12538f723687",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-204e7a9824245987",
    "date": "2026-04-27",
    "kind": "expense",
    "amount": 12.0,
    "category": "Transfers",
    "note": "Zelle to Ella Will",
    "merchant": "Zelle to Ella Will",
    "source": "import",
    "externalId": "chase-204e7a9824245987",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-af32382f32db8ef1",
    "date": "2026-04-27",
    "kind": "expense",
    "amount": 12.0,
    "category": "Transfers",
    "note": "Zelle to Ronni Wieman",
    "merchant": "Zelle to Ronni Wieman",
    "source": "import",
    "externalId": "chase-af32382f32db8ef1",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0f7c171abdc194d6",
    "date": "2026-04-27",
    "kind": "expense",
    "amount": 23.33,
    "category": "Transfers",
    "note": "Zelle to Sam Peterson",
    "merchant": "Zelle to Sam Peterson",
    "source": "import",
    "externalId": "chase-0f7c171abdc194d6",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d546f24cdf90e966",
    "date": "2026-05-01",
    "kind": "expense",
    "amount": 25.8,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-d546f24cdf90e966",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8a27b6115d3609c0",
    "date": "2026-05-01",
    "kind": "income",
    "amount": 21.65,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-8a27b6115d3609c0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ae4447c49131de51",
    "date": "2026-05-01",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-ae4447c49131de51",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9b10069704689433",
    "date": "2026-05-01",
    "kind": "income",
    "amount": 200.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-9b10069704689433",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-dde1d50f52ceb6d3",
    "date": "2026-05-04",
    "kind": "expense",
    "amount": 73.09,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-dde1d50f52ceb6d3",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-aea6b2b9faca8a35",
    "date": "2026-05-04",
    "kind": "expense",
    "amount": 100.0,
    "category": "Other",
    "note": "Goldman Sachs Ba Transfer",
    "merchant": "Goldman Sachs Ba Transfer",
    "source": "import",
    "externalId": "chase-aea6b2b9faca8a35",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-80817eb74d161ce8",
    "date": "2026-05-04",
    "kind": "expense",
    "amount": 25.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-80817eb74d161ce8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-4776e253961089a0",
    "date": "2026-05-05",
    "kind": "income",
    "amount": 40.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-4776e253961089a0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-63a276c1fef3921c",
    "date": "2026-05-11",
    "kind": "expense",
    "amount": 15.76,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-63a276c1fef3921c",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-fad2972ad80b7bb8",
    "date": "2026-05-11",
    "kind": "expense",
    "amount": 93.85,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-fad2972ad80b7bb8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-928cc3f7dfbfbb32",
    "date": "2026-05-11",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-928cc3f7dfbfbb32",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-de3c58af4ecad3bf",
    "date": "2026-05-11",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Goldman Sachs Ba Transfer Shrestha,Melani",
    "merchant": "Goldman Sachs Ba Transfer Shrestha,Melani",
    "source": "import",
    "externalId": "chase-de3c58af4ecad3bf",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-92197669ea9fbb13",
    "date": "2026-05-11",
    "kind": "expense",
    "amount": 10.0,
    "category": "Shopping",
    "note": "Wash Kiosk Mobile 800-4216897 CA",
    "merchant": "Wash Kiosk Mobile 800-4216897 CA",
    "source": "import",
    "externalId": "chase-92197669ea9fbb13",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-6c1ee58c0745f31e",
    "date": "2026-05-11",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-6c1ee58c0745f31e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-5566a1f1749e23d2",
    "date": "2026-05-11",
    "kind": "income",
    "amount": 150.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-5566a1f1749e23d2",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-7730f1ecee98303b",
    "date": "2026-05-11",
    "kind": "expense",
    "amount": 10.0,
    "category": "Transfers",
    "note": "Zelle to Ronni Wieman",
    "merchant": "Zelle to Ronni Wieman",
    "source": "import",
    "externalId": "chase-7730f1ecee98303b",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-13891b5d6834675e",
    "date": "2026-05-12",
    "kind": "income",
    "amount": 19.14,
    "category": "Income",
    "note": "Cash Redemption",
    "merchant": "Cash Redemption",
    "source": "import",
    "externalId": "chase-13891b5d6834675e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-194378218d3f7765",
    "date": "2026-05-13",
    "kind": "expense",
    "amount": 100.85,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-194378218d3f7765",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-71f399794d64c102",
    "date": "2026-05-13",
    "kind": "income",
    "amount": 200.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-71f399794d64c102",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-60e79df78447f980",
    "date": "2026-05-14",
    "kind": "expense",
    "amount": 89.75,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-60e79df78447f980",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-4b44b2c4e45d9dfc",
    "date": "2026-05-14",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-4b44b2c4e45d9dfc",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-5acb4b88a279a5cb",
    "date": "2026-05-14",
    "kind": "income",
    "amount": 200.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-5acb4b88a279a5cb",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d8b6c1fba4e798c3",
    "date": "2026-05-14",
    "kind": "expense",
    "amount": 215.0,
    "category": "Transfers",
    "note": "Zelle to Sean Filimon",
    "merchant": "Zelle to Sean Filimon",
    "source": "import",
    "externalId": "chase-d8b6c1fba4e798c3",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-49b727f0c74af759",
    "date": "2026-05-15",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-49b727f0c74af759",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-7d144ca9f1e04159",
    "date": "2026-05-15",
    "kind": "expense",
    "amount": 118.67,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-7d144ca9f1e04159",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3acae653e56227ad",
    "date": "2026-05-15",
    "kind": "income",
    "amount": 300.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-3acae653e56227ad",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-b777c776300534a0",
    "date": "2026-05-18",
    "kind": "expense",
    "amount": 20.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-b777c776300534a0",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-261e8e0e9c031cba",
    "date": "2026-05-18",
    "kind": "expense",
    "amount": 31.4,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-261e8e0e9c031cba",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-7a2a9593b5f88c37",
    "date": "2026-05-18",
    "kind": "expense",
    "amount": 50.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-7a2a9593b5f88c37",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-27175fd6d07b70a7",
    "date": "2026-05-18",
    "kind": "expense",
    "amount": 200.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-27175fd6d07b70a7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-bfac651962f9114a",
    "date": "2026-05-18",
    "kind": "income",
    "amount": 1.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-bfac651962f9114a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-774d461d82a49064",
    "date": "2026-05-18",
    "kind": "income",
    "amount": 200.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-774d461d82a49064",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ab5849f32d4531ad",
    "date": "2026-05-18",
    "kind": "income",
    "amount": 14.5,
    "category": "Income",
    "note": "Zelle from Richard Leon Coftehfodqy9",
    "merchant": "Zelle from Richard Leon Coftehfodqy9",
    "source": "import",
    "externalId": "chase-ab5849f32d4531ad",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-9e06b4018a469e72",
    "date": "2026-05-18",
    "kind": "expense",
    "amount": 3.0,
    "category": "Transfers",
    "note": "Zelle to Ricky (Coding Guy)",
    "merchant": "Zelle to Ricky (Coding Guy)",
    "source": "import",
    "externalId": "chase-9e06b4018a469e72",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-6e42d64ac081e459",
    "date": "2026-05-22",
    "kind": "income",
    "amount": 5.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-6e42d64ac081e459",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0ba534d1e440bb3e",
    "date": "2026-05-26",
    "kind": "expense",
    "amount": 12.35,
    "category": "Restaurants / coffee",
    "note": "Chipotle 4024 Los Angeles CA",
    "merchant": "Chipotle 4024 Los Angeles CA",
    "source": "import",
    "externalId": "chase-0ba534d1e440bb3e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-661c686c0fb16f9b",
    "date": "2026-05-26",
    "kind": "income",
    "amount": 15.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-661c686c0fb16f9b",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-778b520cc35e3720",
    "date": "2026-05-28",
    "kind": "expense",
    "amount": 70.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-778b520cc35e3720",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-19f982507132b3a7",
    "date": "2026-05-28",
    "kind": "expense",
    "amount": 300.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-19f982507132b3a7",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-68df212b71dc5c3a",
    "date": "2026-05-28",
    "kind": "income",
    "amount": 70.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-68df212b71dc5c3a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-77b73c6ef41c4730",
    "date": "2026-05-28",
    "kind": "income",
    "amount": 300.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-77b73c6ef41c4730",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ddd8fef60bc4cda9",
    "date": "2026-05-29",
    "kind": "expense",
    "amount": 288.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-ddd8fef60bc4cda9",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-95e43a4a2468738e",
    "date": "2026-05-29",
    "kind": "expense",
    "amount": 14.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-95e43a4a2468738e",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-322068c2edaab313",
    "date": "2026-05-29",
    "kind": "income",
    "amount": 124.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-322068c2edaab313",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-dc9fbc16517afcd4",
    "date": "2026-05-29",
    "kind": "income",
    "amount": 300.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-dc9fbc16517afcd4",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-160cb0e967a6a9f6",
    "date": "2026-06-01",
    "kind": "expense",
    "amount": 25.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-160cb0e967a6a9f6",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-ac23b2fbd5cde714",
    "date": "2026-06-05",
    "kind": "expense",
    "amount": 17.57,
    "category": "Transport",
    "note": "Waymo 844-261-3753 CA",
    "merchant": "Waymo 844-261-3753 CA",
    "source": "import",
    "externalId": "chase-ac23b2fbd5cde714",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-eecd8035060cc1ea",
    "date": "2026-06-08",
    "kind": "income",
    "amount": 29.9,
    "category": "Income",
    "note": "Cash Redemption",
    "merchant": "Cash Redemption",
    "source": "import",
    "externalId": "chase-eecd8035060cc1ea",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-733ae55b3783c5c9",
    "date": "2026-06-08",
    "kind": "expense",
    "amount": 29.89,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-733ae55b3783c5c9",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-1eb49660f808021b",
    "date": "2026-06-08",
    "kind": "expense",
    "amount": 29.89,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-1eb49660f808021b",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-d620bf0ff2681a35",
    "date": "2026-06-08",
    "kind": "expense",
    "amount": 40.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-d620bf0ff2681a35",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-2d3052c691234bb4",
    "date": "2026-06-08",
    "kind": "income",
    "amount": 39.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-2d3052c691234bb4",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-0f13d245ffa7d067",
    "date": "2026-06-09",
    "kind": "expense",
    "amount": 30.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-0f13d245ffa7d067",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-1d4aef5dcf80b8f6",
    "date": "2026-06-09",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-1d4aef5dcf80b8f6",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-4c709d6d9e8cae3a",
    "date": "2026-06-09",
    "kind": "expense",
    "amount": 150.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-4c709d6d9e8cae3a",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-5ccebe7c1e1f46c8",
    "date": "2026-06-09",
    "kind": "income",
    "amount": 100.0,
    "category": "Income",
    "note": "Goldman Sachs Ba Transfer Shrestha,Melani",
    "merchant": "Goldman Sachs Ba Transfer Shrestha,Melani",
    "source": "import",
    "externalId": "chase-5ccebe7c1e1f46c8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-f94b514ac93c4e95",
    "date": "2026-06-09",
    "kind": "expense",
    "amount": 10.0,
    "category": "Transfers",
    "note": "To savings",
    "merchant": "To savings",
    "source": "import",
    "externalId": "chase-f94b514ac93c4e95",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c32389843acec1b8",
    "date": "2026-06-09",
    "kind": "income",
    "amount": 150.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-c32389843acec1b8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-52cb451ca4ad5666",
    "date": "2026-06-09",
    "kind": "income",
    "amount": 150.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-52cb451ca4ad5666",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-574b3aaefe61e851",
    "date": "2026-06-10",
    "kind": "expense",
    "amount": 50.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-574b3aaefe61e851",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-c1b36521392ef2fd",
    "date": "2026-06-10",
    "kind": "expense",
    "amount": 100.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-c1b36521392ef2fd",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-5cf7b03d032b279d",
    "date": "2026-06-10",
    "kind": "income",
    "amount": 50.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-5cf7b03d032b279d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-224a0c0e1b1d9f9d",
    "date": "2026-06-10",
    "kind": "income",
    "amount": 23.98,
    "category": "Income",
    "note": "Zelle from Ziyu Gao",
    "merchant": "Zelle from Ziyu Gao",
    "source": "import",
    "externalId": "chase-224a0c0e1b1d9f9d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-bed9b130e910d112",
    "date": "2026-06-11",
    "kind": "expense",
    "amount": 24.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-bed9b130e910d112",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-60344b6df7771f62",
    "date": "2026-06-11",
    "kind": "expense",
    "amount": 45.55,
    "category": "Transfers",
    "note": "Zelle to Ziyu Gao",
    "merchant": "Zelle to Ziyu Gao",
    "source": "import",
    "externalId": "chase-60344b6df7771f62",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-846d4cca5670e076",
    "date": "2026-06-12",
    "kind": "expense",
    "amount": 10.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-846d4cca5670e076",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-1b072dca701f54cf",
    "date": "2026-06-12",
    "kind": "expense",
    "amount": 51.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-1b072dca701f54cf",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-3e8b3afcbc81b01f",
    "date": "2026-06-12",
    "kind": "income",
    "amount": 5.0,
    "category": "Transfers",
    "note": "From savings",
    "merchant": "From savings",
    "source": "import",
    "externalId": "chase-3e8b3afcbc81b01f",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-e5c0890cd7c7992d",
    "date": "2026-06-12",
    "kind": "income",
    "amount": 300.0,
    "category": "Income",
    "note": "Zelle from Bimala Shrestha",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "chase-e5c0890cd7c7992d",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-2ca64351b5eef305",
    "date": "2026-06-12",
    "kind": "income",
    "amount": 51.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-2ca64351b5eef305",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8bdafa008119a1de",
    "date": "2026-06-15",
    "kind": "expense",
    "amount": 300.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-8bdafa008119a1de",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-8fa3cec4a919b7b8",
    "date": "2026-06-22",
    "kind": "expense",
    "amount": 450.0,
    "category": "Transfers",
    "note": "Chase card payment",
    "merchant": "Chase card payment",
    "source": "import",
    "externalId": "chase-8fa3cec4a919b7b8",
    "pending": false,
    "accountId": "acc-chase-checking"
  },
  {
    "id": "chase-90487ddfe9792f96",
    "date": "2026-06-22",
    "kind": "income",
    "amount": 450.0,
    "category": "Income",
    "note": "Zelle from Umesh Shrestha",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "chase-90487ddfe9792f96",
    "pending": false,
    "accountId": "acc-chase-checking"
  }
] as FinanceTx[];

export const CHASE_STATEMENT_ACCOUNTS = [
  { id: "acc-chase-checking", name: "Chase College Checking", kind: "checking" as const, balance: 0.03, institution: "Chase", mask: "8533" },
  { id: "acc-chase-savings", name: "Chase Savings", kind: "savings" as const, balance: 5.0, institution: "Chase", mask: "5591" },
  { id: "acc-chase-card", name: "Chase Card · 5584", kind: "credit" as const, balance: 0, institution: "Chase", mask: "5584", creditLimit: null },
];

export const CHASE_STATEMENT_META = { count: 236, from: "2025-12-08", to: "2026-06-22", source: "Chase statements PDF" };